name: API CI
#on: [push]
on:
  push:
    path:
      "./api/**"
      ".github/workflows/api-ci.yml"

default:
  run:
    working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      name: Checkout
      uses: actions/checkout@v2
      name: Step Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 21
        cache: npm
        cache-dependency-path: ./api/package-lock.json
      name: install
      shell: bash
      run: npm ci
      name: run unit test
      shel: bash
      run: npm run test
